MyCompany/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MyCompany.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Логин")]
        public string UserName { get; set; }

        [Required]
        [UIHint("password")]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        [Display(Name = "Запомнить меня?")]
        public bool RememberMe { get; set; }
    }
}

MyCompany/Models/ViewComponents/SidebarViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;

namespace MyCompany.Models.ViewComponents
{
    public class SidebarViewComponent : ViewComponent
    {
        private readonly DataManager dataManager;

        public SidebarViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            return Task.FromResult((IViewComponentResult) View("Default", dataManager.ServiceItems.GetServiceItems()));
        }
    }
}

MyCompany/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;

namespace MyCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.ServiceItems.GetServiceItems());
        }
    }
}

MyCompany/Areas/Admin/Controllers/ServiceItemsController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Service;

namespace MyCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public ServiceItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new ServiceItem() : dataManager.ServiceItems.GetServiceItemById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(ServiceItem model, string titleImageFile)
        {
            if (ModelState.IsValid)
            {

                model.TitleImagePath = titleImageFile;

                dataManager.ServiceItems.SaveServiceItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.ServiceItems.DeleteServiceItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

MyCompany/Areas/Admin/Controllers/TextFieldsController.cs
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Service;

namespace MyCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TextFieldsController : Controller
    {
        private readonly DataManager dataManager;
        public TextFieldsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Edit(string codeWord)
        {
            var entity = dataManager.TextFields.GetTextFieldByCodeWord(codeWord);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(TextField model)
        {
            if (ModelState.IsValid)
            {
                dataManager.TextFields.SaveTextField(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
    }
}

MyCompany/Controllers/AccountController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Models;

namespace MyCompany.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        public AccountController(UserManager<IdentityUser> userMgr, SignInManager<IdentityUser> signinMgr)
        {
            userManager = userMgr;
            signInManager = signinMgr;
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new LoginViewModel());
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await userManager.FindByNameAsync(model.UserName);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);
                    if (result.Succeeded)
                    {
                        return Redirect(returnUrl ?? "/");
                    }
                }
                ModelState.AddModelError(nameof(LoginViewModel.UserName), "Неверный логин или пароль");
            }
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

MyCompany/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;

namespace MyCompany.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageIndex"));
        }

        public IActionResult Contacts()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageContacts"));
        }
    }
}

MyCompany/Controllers/ServicesController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;

namespace MyCompany.Controllers
{
    public class ServicesController : Controller
    {
        private readonly DataManager dataManager;

        public ServicesController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.ServiceItems.GetServiceItemById(id));
            }

            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageServices");
            return View(dataManager.ServiceItems.GetServiceItems());
        }
    }
}

MyCompany/Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<ServiceItem>
@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}

<div>
    <h2>@strTitle</h2>
    <div>
        <h3>Наши услуги</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="">Добавить услугу</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (ServiceItem entity in Model)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="@entity.Id">редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="ServiceItems" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">удалить</a>
                        </form>
                        |
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Title}")
                        </a>
                    </div>
                }
            </div>
        }
    </div>
    <div class="div-box">
        <h3>Редактировать страницы сайта</h3>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageServices">Наши услуги</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
    </div>
    <div class="div-box">
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Выйти" />
        </form>
    </div>
</div>

MyCompany/Areas/Admin/Views/ServiceItems/Edit.cshtml
@model ServiceItem
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Subtitle"></label>
                <input asp-for="Subtitle" />
                <span asp-validation-for="Subtitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="text" name="titleImageFile" id="titleImageFile" />
                <span asp-validation-for="TitleImagePath"></span>
                <div>
                    <img class="img-block" src="@Model.TitleImagePath"/>
                </div>
            </div>
           @* <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.TitleImagePath" />
                </div>
            </div>*@
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

MyCompany/Areas/Admin/Views/TextFields/Edit.cshtml
@model TextField
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="TextFields" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="CodeWord" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

MyCompany/Views/Home/Contacts.cshtml
@model TextField
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
     <section class="contact-page-section">
      <div class="container">
          <div class="sec-title">
            </div>
            <div class="inner-container">
              <div class="row clearfix">
                
                    <!--Info Column-->
                    <div class="info-column col-md-4 col-sm-12 col-xs-12">
                      <div class="inner-column">
                          <h2 style="color: #fff">Contact Info</h2>
                            <ul class="list-info">
                                <li style="color: #fff"><i class="fas fa-phone"></i>+38 (098) 127-65-69 - Ігор</li>
                                <li style="color: #fff"><i class="fas fa-phone"></i>+38 (050) 508-94-74 - Ігор</li>
                            </ul>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </section>
    @Html.Raw(Model.Text)
</div>

MyCompany/Views/Home/Index.cshtml
@model TextField
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>

    @await Html.PartialAsync("Carousel")
                        @await Html.PartialAsync("SidebarPartial")

    @await Html.PartialAsync("Slider")
    <div class="card bg-light mb-3">
        <div class="card-body">
            <h5 class="card-title">Про нас</h5>
            <p class="card-text">
                Наша служба – це сервіс вирішення будь-яких побутових проблем у Рівному. Компанія надає кваліфіковані послуги електриків, сантехніків, майстрів пральних машин та іншої малої побутової техніки.<br>
                Для клієнтів сервіс підготував кілька переваг:<br>
                • надання послуг в зручний клієнтам час<br>
                • знижки постійним замовникам;<br>
                <br>

                Домовий сервіс займається швидким та ефективним вирішенням будь-яких побутових проблем. Компанія пропонує:<br>
                - ремонт побутової техніки<br>
                - послуги електрика, сантехніка<br>
                - встановлення та налаштування побутової техніки та побутового обладнання;<br>
                - ремонт сантехнічного та іншого побутового обладнання;<br>
                - консультаційні послуги;<br>
                - продаж, купівля б/у пральних машин<br>
                Зламалася пральна машина, а в кошику нагромадилося багато брудного одягу? Потрібно терміново випрати речі?  Не проблема! Наш Домовий сервіс стане Вашою чарівною паличкою, яка вирішить будь-яку побутову проблему у Рівному.
            </p>
        </div>
    </div>
</div>

MyCompany/Views/Services/Index.cshtml
@model IQueryable<ServiceItem>
@{
    TextField textField = ViewBag.TextField;

    ViewBag.Title = textField.MetaTitle;
    ViewBag.Description = textField.MetaDescription;
    ViewBag.Keywords = textField.MetaKeywords;
}

<div>
    @if (Model.Any())
    {
        <ul class="big-image-list">
            @foreach (ServiceItem entity in Model)
            {
                <li>

                    <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                        <img src="@entity.TitleImagePath" alt="" class="left" />
                    </a>
                    <h4 style="color: #fff">@entity.Title</h4>
                    <p style="color: #fff">@entity.Subtitle</p>
                </li>
            }
        </ul>
    }
</div>

MyCompany/Views/Services/Show.cshtml
@model ServiceItem
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

@*<div>
    <h2>
        @Model.Title
    </h2>
    <h2>
        @Model.Subtitle
    </h2>
    <div>
        <img class="img-block" src="@Model.TitleImagePath" />
    </div>
</div>
<div>
    @Html.Raw(Model.Text)
</div>*@

<div class="card mb-3">
  <img class="card-img-top" src="@Model.TitleImagePath" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">@Model.Title</h5>
    <p class="card-text">@Html.Raw(Model.Text)</p>
    <p class="card-text"><small class="text-muted">@Model.Subtitle</small></p>
  </div>
</div>

MyCompany/Views/Shared/Carousel.cshtml
<div data-aos="fade-right" class="card mb-3 center">
    <div class="row no-gutters">
        <div class="col-md-8">
            <img src="~/CardImages/remonttexniki.webp"
                 class="card-img" alt="...">
        </div>
        <div class="col-md-4">
            <div class="card-body">
                <h4 class="card-title">Терміновий ремонт малої побутової техніки у Рівному</h4>
                <h5 class="card-subtitle">у 90% випадків ремонт у день звернення!</h5>
                <br />
                <p> Ми пропонуємо Вам швидкий та якісний ремонт як малої, так і великої побутової техніки різних брендів за максимально доступну ціну. Скориставшись нашими послугами, Ви на власному досвіді переконаєтесь, як має виглядати справжній знак якості. Адже ми виконуємо для Вас ремонт техніки на найвищому рівні.</p>
                <a href="Services" class="btn btn-primary">Наші послуги</a>
            </div>
        </div>
    </div>
</div>

MyCompany/Views/Shared/Components/Sidebar/Default.cshtml
@model IQueryable<ServiceItem>

@if (Model?.Any() == true)
{
    <h2 style="color: #fff">Наші послуги</h2>
    <div class="card-deck">
        @foreach (ServiceItem entity in Model)
        {
            <div class="card text-white bg-info mb-3">
                <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                    <img class="card-img-top" src="@entity.TitleImagePath" alt="Card image cap">
                </a>

                <div class="card-body">
                    <h5 class="card-title">@entity.Title</h5>
                    <p class="card-text">@entity.Subtitle</p>
                </div>
            </div>

        }
    </div>
}

MyCompany/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/icons.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/Logo.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/slider.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/scroll.css" asp-append-version="true" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

MyCompany/Views/Shared/FooterPartial.cshtml
<!-- Footer -->
<div style="background: #fff" id="footer-wrapper">
    <div class="container">
        <div class="row">
            <div >

                <section>
                    <div class="card text-center text-white bg-dark mb-3">
                        <div class="card-header">
                            Як з нами зв'язатись?'
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">Наші контакти</h5>
                            <ul>
                                <li><a style="color:white;" href="tel:+380981276569">+38 (098) 127-65-69 - Ігор</a></li>
                                <li><a style="color:white;" href="tel:+380981276569">+38 (050) 508-94-74 - Ігор</a></li>
                                <li><a style="color:white;" href="#"">vigovskiy1979@gmail.com</a></li>
                                <li><a style="color:white;" href="#">Вирішення Ваших побутових проблем по одному номеру </a></li>
                                <li><a style="color:white;" href="#">Всі деталі послуг можна отримати в дзвінку</a></li>
                            </ul>                            
                            <a href="" class="btn btn-primary">Головна</a>
                        </div>
                    </div>
                    @*<h2>Наші контакти</h2>
                        <div>
                        <div class="row">
                        <div class="col-3 col-6-medium col-12-small">
                        <ul class="link-list">
                        <li><a href="#">+38 (068) 100-78-12 - Юрій</a></li>
                        <li><a href="#">+38 (093) 361-97-07 - Юрій</a></li>
                        <li><a href="#">+38 (098) 127-65-69 - Ігор</a></li>
                        <li><a href="#">Вірішення ваших побутових проблем по одному номеру </a></li>
                        <li><a href="#">Всі деталі послуг можна отримати в дзвінку</a></li>
                        </ul>
                        </div>
                        <div class="col-3 col-6-medium col-12-small">
                        <ul class="link-list">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Головна</a></li>
                        <li><a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="">Наші послуги</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contacts">Наші контакти</a></li>
                        </ul>
                        </div>

                        </div>
                        </div>*@
                </section>

            </div>

        </div>
    </div>
</div>

MyCompany/Views/Shared/HeaderPartial.cshtml
<div id="header-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">

@*                <img src="images/logo.png" alt="" width="150" height="150" style="margin-left:500px" />
*@                <header id="header">

                    <h1><a href="/" id="logo">@Config.CompanyName</a> </h1>


                    <nav id="nav">
                        <a asp-area="" asp-controller="Home" asp-action="Index">Головна</a>
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="">Наші послуги</a>
                        <a asp-area="" asp-controller="Home" asp-action="Contacts">Контакти</a>
                    </nav>
                </header>

            </div>
        </div>
    </div>
</div>

MyCompany/Views/Shared/MetatagsPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
@if (ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>@Config.CompanyName</title>
}
@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}
@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords" />
}

MyCompany/Views/Shared/ScriptsPartial.cshtml
<script src="~/js/scripts.min.js" asp-append-version="true"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

MyCompany/Views/Shared/SidebarPartial.cshtml
<div class="col-12 col-12-medium">
    <cache>
        @(await Component.InvokeAsync<SidebarViewComponent>())
    </cache>
</div>

MyCompany/Views/Shared/Slider.cshtml
<br>

<div class="card-deck">

    <div class="card">
        <img class="card-img-top" src="/CardImages/Pilesos.jpg" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Ремонт пилососів</h5>
            <ul>
                <li>Всі послуги та перелік техніки, яку ми ремонтуємо Ви можете дізнатися по телефону</li>
            </ul>
        </div>
        <a href="Home/Contacts" class="btn btn-primary">Зв'язатись з нами</a>
    </div>

    <div class="card">
        <img class="card-img-top" src="/CardImages/microvoln.webp" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Ремонт мікрохвильовок</h5>
            <ul>
                <li>Всі послуги та перелік техніки, яку ми ремонтуємо Ви можете дізнатися по телефону</li>
            </ul>
        </div>
        <a href="Home/Contacts" class="btn btn-primary">Зв'язатись з нами</a>

    </div>
    <div class="card">
        <img class="card-img-top" src="/CardImages/obogrevatel.jpg" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Ремонт обігрівачів</h5>
            <ul>
                <li>Всі послуги та перелік техніки, яку ми ремонтуємо Ви можете дізнатися по телефону</li>
            </ul>
        </div>
        <a href="Home/Contacts" class="btn btn-primary">Зв'язатись з нами</a>
    </div>
</div>
<br>

<h1 style="color: white">Можливі несправності</h1>
<div class="card-deck">

    <div class="card">
        <img class="card-img-top" src="/CardImages/NeGrie.png" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Не гріє воду</h5>
            <ul>
                <li>Вийшов з ладу ТЕН</li>
                <li>Зламався датчик температури</li>
                <li>Збої в модулі управління або програматорі</li>
            </ul>
        </div>
        <a href="Home/Contacts" class="btn btn-primary">Зв'язатись з нами</a>
    </div>
    <div class="card">
        <img class="card-img-top" src="/CardImages/sliv.jpg" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Не зливаєтсья вода</h5>
            <ul>
                <li>Вийшов з ладу насос</li>
                <li>Несправності датчика рівня води</li>
                <li>Засмітився фільтр зливу води або патрубок</li>
                <li>Збої у модулі управління</li>
            </ul>
        </div>
        <a href="Home/Contacts" class="btn btn-primary">Зв'язатись з нами</a>
    </div>
    <div class="card">
        <img class="card-img-top" src="/CardImages/protechka.jpg" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Протікає</h5>
            <ul>
                <li>Забруднення дозатора миючих засобів</li>
                <li>Манжета люка зносилася</li>
                <li>Поломка патрубка</li>
            </ul>
        </div>
        <a href="Home/Contacts" class="btn btn-primary">Зв'язатись з нами</a>
    </div>

</div>

<br>

MyCompany/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    @await Html.PartialAsync("MetatagsPartial")
    <link rel="stylesheet" href="~/css/carousel.css asp-append-version="true" />
    @await Html.PartialAsync("CssPartial")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>
<body>
    <div id="page-wrapper">
        @await Html.PartialAsync("HeaderPartial")
        <div class="card" style="background-color: #191919">
            <div class="card-body" style="text-align: center">
                <a href="tel:+380981276569"><h3 style="text-transform: capitalize;">+38 (098) 127-65-69 - Ігор</h3></a>
                <a href="tel:+380981276569"><h3 style="text-transform: capitalize;">+38 (050) 508-94-74 - Ігор</h3></a><br/>
                <h3 style="color: white; text-transform: uppercase;">Вирішимо всі ваші проблеми швидко та без нервів!</h3>
                <h3 style="color: white; text-transform: uppercase;">Таких цін ви не знайдете ніде!</h3>
            </div>
        </div>
        <div id="main">
            <div class="container">
                <div class="row main-row">
                    <div class="col-12 col-12-medium">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
        @await Html.PartialAsync("FooterPartial")
    </div>
    @await Html.PartialAsync("ScriptsPartial")
</body>

</html>